name: sync traefik config files

on:
  push:
    branches:
    - master
    paths:
    - files/config/**

  pull_request:
    types:
    - closed
    branches:
    - master
    paths:
    - files/config/**



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZ_ACCOUNT_CRED }}

    - name: Upload to file share
      uses: azure/CLI@v2
      with:
        inlineScript: |
          ls
          az account show
          az storage file upload-batch --account-name datastore4ci --account-key ${{ secrets.AZ_STORAGE_KEY }} --share-name fs4proxymanager --name config --auth-mode key --overwrite -d './config' -s 'files/config/'

        # Azure logout
    - name: logout
      run: |
        az logout
      if: always()

